//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotizacion()
        {
            this.CotizacionFuncion = new HashSet<CotizacionFuncion>();
            this.DescripcionHechura = new HashSet<DescripcionHechura>();
        }
    
        public int IdCotizacion { get; set; }
        public int IdCliente { get; set; }
        public int IdEstado { get; set; }
        public Nullable<System.DateTime> FechaImpresion { get; set; }
        public string UsuarioImpresion { get; set; }
        public string Cod_RA { get; set; }
        public byte diasEntrega { get; set; }
        public int IdPrecioEnergiaElectrica { get; set; }
        public string PorcentajeAvance { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual PrecioEnergia PrecioEnergia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizacionFuncion> CotizacionFuncion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescripcionHechura> DescripcionHechura { get; set; }
    }
}
