//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescripcionHechura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DescripcionHechura()
        {
            this.AccesorioDescripcionHechura = new HashSet<AccesorioDescripcionHechura>();
            this.CombinacionDescripcionHechura = new HashSet<CombinacionDescripcionHechura>();
            this.DescripcionHechuraColor = new HashSet<DescripcionHechuraColor>();
            this.ListadoProduccion = new HashSet<ListadoProduccion>();
            this.PrecioMIDescripcionHechura = new HashSet<PrecioMIDescripcionHechura>();
        }
    
        public int IdDescripcionHechura { get; set; }
        public int IdCotizacion { get; set; }
        public int IdPieza { get; set; }
        public int IdTela { get; set; }
        public int CantidadRequerida { get; set; }
        public double Duracion { get; set; }
        public double CostoUnit { get; set; }
        public string Descripcion { get; set; }
        public bool regAnulado { get; set; }
        public string cod_RA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccesorioDescripcionHechura> AccesorioDescripcionHechura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CombinacionDescripcionHechura> CombinacionDescripcionHechura { get; set; }
        public virtual Cotizacion Cotizacion { get; set; }
        public virtual PrecioTelaDescripcionHechura PrecioTelaDescripcionHechura { get; set; }
        public virtual Pieza Pieza { get; set; }
        public virtual Tela Tela { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescripcionHechuraColor> DescripcionHechuraColor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListadoProduccion> ListadoProduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrecioMIDescripcionHechura> PrecioMIDescripcionHechura { get; set; }
    }
}
