//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleNomina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleNomina()
        {
            this.OtroIngresoEgreso = new HashSet<OtroIngresoEgreso>();
        }
    
        public int IdDetalleNomina { get; set; }
        public int IdNomina { get; set; }
        public int IdEmpleado { get; set; }
        public double SalarioBase { get; set; }
        public double SeptimoDia { get; set; }
        public Nullable<double> Viaticos { get; set; }
        public double Ajuste { get; set; }
        public double Transporte { get; set; }
        public byte HorasExtra { get; set; }
        public Nullable<double> TotalOtrosIngresos { get; set; }
        public byte Ausencia { get; set; }
        public int MinutosTarde { get; set; }
        public double Prestamo { get; set; }
        public double INSS { get; set; }
        public bool regAnulado { get; set; }
        public Nullable<double> TotalOtrosEgresos { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Nomina Nomina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtroIngresoEgreso> OtroIngresoEgreso { get; set; }
    }
}
