//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleListadoProduccion
    {
        public int IdDetalleListadoProduccion { get; set; }
        public int IdListadoProduccion { get; set; }
        public int IdMedida { get; set; }
        public double Medida { get; set; }
        public bool regAnulado { get; set; }
    
        public virtual ListadoProduccion ListadoProduccion { get; set; }
        public virtual Medida Medida1 { get; set; }
    }
}
