//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntregaTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntregaTicket()
        {
            this.PrecioCombinacionEntregaTicket = new HashSet<PrecioCombinacionEntregaTicket>();
        }
    
        public int IdEntregaTicket { get; set; }
        public int IdListadoProduccion { get; set; }
        public int IdEmpleado { get; set; }
        public string NombreFuncion { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public Nullable<int> IdNomina { get; set; }
        public Nullable<int> IdEstadoReemplaza { get; set; }
        public string Usuario { get; set; }
        public bool regAnulado { get; set; }
        public Nullable<double> MOCombinaciones { get; set; }
        public Nullable<double> MOPieza { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Funcion Funcion { get; set; }
        public virtual ListadoProduccion ListadoProduccion { get; set; }
        public virtual Nomina Nomina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrecioCombinacionEntregaTicket> PrecioCombinacionEntregaTicket { get; set; }
        public virtual PrecioPiezaEntregaTicket PrecioPiezaEntregaTicket { get; set; }
    }
}
