//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoEnergia
    {
        public int IdGastoEnergia { get; set; }
        public double Monto { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime MesAplica { get; set; }
        public string FacturaNo { get; set; }
    }
}
