//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListadoProduccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListadoProduccion()
        {
            this.DetalleListadoProduccion = new HashSet<DetalleListadoProduccion>();
            this.EntregaTicket = new HashSet<EntregaTicket>();
            this.TickectPrecioReparacion = new HashSet<TickectPrecioReparacion>();
        }
    
        public int IdListadoProduccion { get; set; }
        public int IdDescripcionHechura { get; set; }
        public int IdTalla { get; set; }
        public int IdColor { get; set; }
        public string Nombre { get; set; }
        public int Cantidad { get; set; }
        public int IdEstado { get; set; }
        public bool isReparacion { get; set; }
        public string Observaciones { get; set; }
        public string cod_RA { get; set; }
        public bool regAnulado { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual DescripcionHechura DescripcionHechura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleListadoProduccion> DetalleListadoProduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntregaTicket> EntregaTicket { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Talla Talla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TickectPrecioReparacion> TickectPrecioReparacion { get; set; }
    }
}
