//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logErrores
    {
        public int idError { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string idUser { get; set; }
        public string URL { get; set; }
    }
}
