//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaquinariaEquipoElectrico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaquinariaEquipoElectrico()
        {
            this.ProduccionEquipoElectrico = new HashSet<ProduccionEquipoElectrico>();
        }
    
        public int IdMaquinariaEquipoElectrico { get; set; }
        public string NombreEquipo { get; set; }
        public string NombreFuncion { get; set; }
        public double ConsumoPromedioKWh { get; set; }
        public byte CantidadExistencia { get; set; }
        public bool isMaquinaria { get; set; }
        public bool regAnulado { get; set; }
    
        public virtual Funcion Funcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduccionEquipoElectrico> ProduccionEquipoElectrico { get; set; }
    }
}
