//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConfortexEntities : DbContext
    {
        public ConfortexEntities()
            : base("name=ConfortexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<logErrores> logErrores { get; set; }
        public virtual DbSet<RegistroAcciones> RegistroAcciones { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Accesorio> Accesorio { get; set; }
        public virtual DbSet<AccesorioDescripcionHechura> AccesorioDescripcionHechura { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Cliente_Persona> Cliente_Persona { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Combinacion> Combinacion { get; set; }
        public virtual DbSet<CombinacionDescripcionHechura> CombinacionDescripcionHechura { get; set; }
        public virtual DbSet<Cotizacion> Cotizacion { get; set; }
        public virtual DbSet<CotizacionFuncion> CotizacionFuncion { get; set; }
        public virtual DbSet<DescripcionHechura> DescripcionHechura { get; set; }
        public virtual DbSet<DescripcionHechuraColor> DescripcionHechuraColor { get; set; }
        public virtual DbSet<DetalleListadoProduccion> DetalleListadoProduccion { get; set; }
        public virtual DbSet<DetalleNomina> DetalleNomina { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<EntregaTicket> EntregaTicket { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Funcion> Funcion { get; set; }
        public virtual DbSet<GastoEnergia> GastoEnergia { get; set; }
        public virtual DbSet<ListadoProduccion> ListadoProduccion { get; set; }
        public virtual DbSet<MaquinariaEquipoElectrico> MaquinariaEquipoElectrico { get; set; }
        public virtual DbSet<Medida> Medida { get; set; }
        public virtual DbSet<Nomina> Nomina { get; set; }
        public virtual DbSet<NominaDiaLibre> NominaDiaLibre { get; set; }
        public virtual DbSet<OperadoraTelefonica> OperadoraTelefonica { get; set; }
        public virtual DbSet<OtroIngresoEgreso> OtroIngresoEgreso { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Pieza> Pieza { get; set; }
        public virtual DbSet<PiezaAccesorio> PiezaAccesorio { get; set; }
        public virtual DbSet<PiezaMedida> PiezaMedida { get; set; }
        public virtual DbSet<PiezaTalla> PiezaTalla { get; set; }
        public virtual DbSet<PiezaTallaMedida_Standar> PiezaTallaMedida_Standar { get; set; }
        public virtual DbSet<PrecioAccesorio> PrecioAccesorio { get; set; }
        public virtual DbSet<PrecioCombinacion> PrecioCombinacion { get; set; }
        public virtual DbSet<PrecioCombinacionEntregaTicket> PrecioCombinacionEntregaTicket { get; set; }
        public virtual DbSet<PrecioEnergia> PrecioEnergia { get; set; }
        public virtual DbSet<PrecioMIDescripcionHechura> PrecioMIDescripcionHechura { get; set; }
        public virtual DbSet<PrecioPieza> PrecioPieza { get; set; }
        public virtual DbSet<PrecioPiezaEntregaTicket> PrecioPiezaEntregaTicket { get; set; }
        public virtual DbSet<PrecioTela> PrecioTela { get; set; }
        public virtual DbSet<PrecioTelaDescripcionHechura> PrecioTelaDescripcionHechura { get; set; }
        public virtual DbSet<ProduccionEquipoElectrico> ProduccionEquipoElectrico { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Talla> Talla { get; set; }
        public virtual DbSet<Tela> Tela { get; set; }
        public virtual DbSet<TickectPrecioReparacion> TickectPrecioReparacion { get; set; }
        public virtual DbSet<Pantalla> Pantalla { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<PermisoName> PermisoName { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioClaim> UsuarioClaim { get; set; }
        public virtual DbSet<UsuarioLogin> UsuarioLogin { get; set; }
        public virtual DbSet<UsuarioRol> UsuarioRol { get; set; }
        public virtual DbSet<vw__ObtenerDetalleTickets> vw__ObtenerDetalleTickets { get; set; }
        public virtual DbSet<vw_ListadoMaterialesCotizacion> vw_ListadoMaterialesCotizacion { get; set; }
        public virtual DbSet<vw_ListadoTelasCotizacion> vw_ListadoTelasCotizacion { get; set; }
        public virtual DbSet<vw_ObtenerAccesorios> vw_ObtenerAccesorios { get; set; }
        public virtual DbSet<vw_ObtenerClientes> vw_ObtenerClientes { get; set; }
        public virtual DbSet<vw_ObtenerCombinaciones> vw_ObtenerCombinaciones { get; set; }
        public virtual DbSet<vw_ObtenerCotizaciones> vw_ObtenerCotizaciones { get; set; }
        public virtual DbSet<vw_ObtenerDetalleCotizacion> vw_ObtenerDetalleCotizacion { get; set; }
        public virtual DbSet<vw_ObtenerDetallesNomina> vw_ObtenerDetallesNomina { get; set; }
        public virtual DbSet<vw_ObtenerEmpleados> vw_ObtenerEmpleados { get; set; }
        public virtual DbSet<vw_ObtenerEncabezadoPieCotizacion> vw_ObtenerEncabezadoPieCotizacion { get; set; }
        public virtual DbSet<vw_ObtenerEntregas> vw_ObtenerEntregas { get; set; }
        public virtual DbSet<vw_ObtenerGastoMensual> vw_ObtenerGastoMensual { get; set; }
        public virtual DbSet<vw_ObtenerInfoEmpresa> vw_ObtenerInfoEmpresa { get; set; }
        public virtual DbSet<vw_ObtenerTelas> vw_ObtenerTelas { get; set; }
        public virtual DbSet<vw_ObtenerNomina> vw_ObtenerNomina { get; set; }
    
        [DbFunction("ConfortexEntities", "Cod_RA_Table")]
        public virtual IQueryable<Cod_RA_Table_Result> Cod_RA_Table()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Cod_RA_Table_Result>("[ConfortexEntities].[Cod_RA_Table]()");
        }
    
        [DbFunction("ConfortexEntities", "fn_ObtenerColoresDescHechura")]
        public virtual IQueryable<fn_ObtenerColoresDescHechura_Result> fn_ObtenerColoresDescHechura(Nullable<int> idDescripcionHechura)
        {
            var idDescripcionHechuraParameter = idDescripcionHechura.HasValue ?
                new ObjectParameter("IdDescripcionHechura", idDescripcionHechura) :
                new ObjectParameter("IdDescripcionHechura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ObtenerColoresDescHechura_Result>("[ConfortexEntities].[fn_ObtenerColoresDescHechura](@IdDescripcionHechura)", idDescripcionHechuraParameter);
        }
    
        [DbFunction("ConfortexEntities", "fn_ObtenerDescripcionHechura")]
        public virtual IQueryable<fn_ObtenerDescripcionHechura_Result> fn_ObtenerDescripcionHechura(Nullable<int> idDescripcionHechura, Nullable<bool> accesorio)
        {
            var idDescripcionHechuraParameter = idDescripcionHechura.HasValue ?
                new ObjectParameter("IdDescripcionHechura", idDescripcionHechura) :
                new ObjectParameter("IdDescripcionHechura", typeof(int));
    
            var accesorioParameter = accesorio.HasValue ?
                new ObjectParameter("Accesorio", accesorio) :
                new ObjectParameter("Accesorio", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ObtenerDescripcionHechura_Result>("[ConfortexEntities].[fn_ObtenerDescripcionHechura](@IdDescripcionHechura, @Accesorio)", idDescripcionHechuraParameter, accesorioParameter);
        }
    
        [DbFunction("ConfortexEntities", "fn_ObtenerEmpleadosNomina")]
        public virtual IQueryable<fn_ObtenerEmpleadosNomina_Result> fn_ObtenerEmpleadosNomina(Nullable<int> idNomina)
        {
            var idNominaParameter = idNomina.HasValue ?
                new ObjectParameter("IdNomina", idNomina) :
                new ObjectParameter("IdNomina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ObtenerEmpleadosNomina_Result>("[ConfortexEntities].[fn_ObtenerEmpleadosNomina](@IdNomina)", idNominaParameter);
        }
    
        [DbFunction("ConfortexEntities", "fn_ObtenerMIPrecioConsignado")]
        public virtual IQueryable<fn_ObtenerMIPrecioConsignado_Result> fn_ObtenerMIPrecioConsignado(Nullable<int> idCotizacion)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ObtenerMIPrecioConsignado_Result>("[ConfortexEntities].[fn_ObtenerMIPrecioConsignado](@IdCotizacion)", idCotizacionParameter);
        }
    
        [DbFunction("ConfortexEntities", "fn_ObtenerPagoTrabajador")]
        public virtual IQueryable<fn_ObtenerPagoTrabajador_Result> fn_ObtenerPagoTrabajador(Nullable<int> idEmpleado, Nullable<int> idNomina)
        {
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("IdEmpleado", idEmpleado) :
                new ObjectParameter("IdEmpleado", typeof(int));
    
            var idNominaParameter = idNomina.HasValue ?
                new ObjectParameter("IdNomina", idNomina) :
                new ObjectParameter("IdNomina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ObtenerPagoTrabajador_Result>("[ConfortexEntities].[fn_ObtenerPagoTrabajador](@IdEmpleado, @IdNomina)", idEmpleadoParameter, idNominaParameter);
        }
    
        [DbFunction("ConfortexEntities", "fn_ObtenerTelaPrecioConsignado")]
        public virtual IQueryable<fn_ObtenerTelaPrecioConsignado_Result> fn_ObtenerTelaPrecioConsignado(Nullable<int> idCotizacion)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ObtenerTelaPrecioConsignado_Result>("[ConfortexEntities].[fn_ObtenerTelaPrecioConsignado](@IdCotizacion)", idCotizacionParameter);
        }
    
        [DbFunction("ConfortexEntities", "fn_ObtenerTickets")]
        public virtual IQueryable<fn_ObtenerTickets_Result> fn_ObtenerTickets(Nullable<int> idDescripcionHechura)
        {
            var idDescripcionHechuraParameter = idDescripcionHechura.HasValue ?
                new ObjectParameter("IdDescripcionHechura", idDescripcionHechura) :
                new ObjectParameter("IdDescripcionHechura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ObtenerTickets_Result>("[ConfortexEntities].[fn_ObtenerTickets](@IdDescripcionHechura)", idDescripcionHechuraParameter);
        }
    
        [DbFunction("ConfortexEntities", "fn_ObtenerTrabajadoresNomina")]
        public virtual IQueryable<fn_ObtenerTrabajadoresNomina_Result> fn_ObtenerTrabajadoresNomina(Nullable<int> idNomina)
        {
            var idNominaParameter = idNomina.HasValue ?
                new ObjectParameter("IdNomina", idNomina) :
                new ObjectParameter("IdNomina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ObtenerTrabajadoresNomina_Result>("[ConfortexEntities].[fn_ObtenerTrabajadoresNomina](@IdNomina)", idNominaParameter);
        }
    
        [DbFunction("ConfortexEntities", "fn_ObtenerValorMedida")]
        public virtual IQueryable<fn_ObtenerValorMedida_Result> fn_ObtenerValorMedida(Nullable<int> idMedida, Nullable<int> idListadoProduccion)
        {
            var idMedidaParameter = idMedida.HasValue ?
                new ObjectParameter("IdMedida", idMedida) :
                new ObjectParameter("IdMedida", typeof(int));
    
            var idListadoProduccionParameter = idListadoProduccion.HasValue ?
                new ObjectParameter("IdListadoProduccion", idListadoProduccion) :
                new ObjectParameter("IdListadoProduccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ObtenerValorMedida_Result>("[ConfortexEntities].[fn_ObtenerValorMedida](@IdMedida, @IdListadoProduccion)", idMedidaParameter, idListadoProduccionParameter);
        }
    
        [DbFunction("ConfortexEntities", "fn_PrecioSugerido")]
        public virtual IQueryable<fn_PrecioSugerido_Result> fn_PrecioSugerido(Nullable<int> idDescripcionHechura)
        {
            var idDescripcionHechuraParameter = idDescripcionHechura.HasValue ?
                new ObjectParameter("IdDescripcionHechura", idDescripcionHechura) :
                new ObjectParameter("IdDescripcionHechura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_PrecioSugerido_Result>("[ConfortexEntities].[fn_PrecioSugerido](@IdDescripcionHechura)", idDescripcionHechuraParameter);
        }
    
        [DbFunction("ConfortexEntities", "fn_menu")]
        public virtual IQueryable<fn_menu_Result> fn_menu(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_menu_Result>("[ConfortexEntities].[fn_menu](@user)", userParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_AsociarPreciosAccesorio(Nullable<int> idCotizacion, Nullable<int> idAccesorio, Nullable<bool> mantenerPrecio, Nullable<double> precioNuevo)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            var idAccesorioParameter = idAccesorio.HasValue ?
                new ObjectParameter("IdAccesorio", idAccesorio) :
                new ObjectParameter("IdAccesorio", typeof(int));
    
            var mantenerPrecioParameter = mantenerPrecio.HasValue ?
                new ObjectParameter("MantenerPrecio", mantenerPrecio) :
                new ObjectParameter("MantenerPrecio", typeof(bool));
    
            var precioNuevoParameter = precioNuevo.HasValue ?
                new ObjectParameter("PrecioNuevo", precioNuevo) :
                new ObjectParameter("PrecioNuevo", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AsociarPreciosAccesorio", idCotizacionParameter, idAccesorioParameter, mantenerPrecioParameter, precioNuevoParameter);
        }
    
        public virtual int sp_AsociarPreciosTela(Nullable<int> idCotizacion, Nullable<int> idTela, Nullable<bool> mantenerPrecio, Nullable<double> precioNuevo)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            var idTelaParameter = idTela.HasValue ?
                new ObjectParameter("IdTela", idTela) :
                new ObjectParameter("IdTela", typeof(int));
    
            var mantenerPrecioParameter = mantenerPrecio.HasValue ?
                new ObjectParameter("MantenerPrecio", mantenerPrecio) :
                new ObjectParameter("MantenerPrecio", typeof(bool));
    
            var precioNuevoParameter = precioNuevo.HasValue ?
                new ObjectParameter("PrecioNuevo", precioNuevo) :
                new ObjectParameter("PrecioNuevo", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AsociarPreciosTela", idCotizacionParameter, idTelaParameter, mantenerPrecioParameter, precioNuevoParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_EntregarTicket(Nullable<int> idTicket, string actividad, Nullable<int> idEmpleado, Nullable<int> idEntrega)
        {
            var idTicketParameter = idTicket.HasValue ?
                new ObjectParameter("IdTicket", idTicket) :
                new ObjectParameter("IdTicket", typeof(int));
    
            var actividadParameter = actividad != null ?
                new ObjectParameter("Actividad", actividad) :
                new ObjectParameter("Actividad", typeof(string));
    
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("IdEmpleado", idEmpleado) :
                new ObjectParameter("IdEmpleado", typeof(int));
    
            var idEntregaParameter = idEntrega.HasValue ?
                new ObjectParameter("IdEntrega", idEntrega) :
                new ObjectParameter("IdEntrega", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EntregarTicket", idTicketParameter, actividadParameter, idEmpleadoParameter, idEntregaParameter);
        }
    
        public virtual int sp_GestionarAccesorio(Nullable<int> idAccesorio, string nombre, Nullable<bool> isAccesorio, Nullable<double> precio, string descripcion, Nullable<byte> accion)
        {
            var idAccesorioParameter = idAccesorio.HasValue ?
                new ObjectParameter("IdAccesorio", idAccesorio) :
                new ObjectParameter("IdAccesorio", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var isAccesorioParameter = isAccesorio.HasValue ?
                new ObjectParameter("isAccesorio", isAccesorio) :
                new ObjectParameter("isAccesorio", typeof(bool));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(double));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GestionarAccesorio", idAccesorioParameter, nombreParameter, isAccesorioParameter, precioParameter, descripcionParameter, accionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_GestionarCombinacion(Nullable<int> idCombinacion, string nombre, string descripcion, Nullable<double> cantidadTela, Nullable<byte> accion)
        {
            var idCombinacionParameter = idCombinacion.HasValue ?
                new ObjectParameter("IdCombinacion", idCombinacion) :
                new ObjectParameter("IdCombinacion", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var cantidadTelaParameter = cantidadTela.HasValue ?
                new ObjectParameter("CantidadTela", cantidadTela) :
                new ObjectParameter("CantidadTela", typeof(double));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_GestionarCombinacion", idCombinacionParameter, nombreParameter, descripcionParameter, cantidadTelaParameter, accionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_GestionarCotizacion(Nullable<int> idCotizacion, Nullable<int> idCliente, Nullable<int> idEstado, Nullable<byte> accion, Nullable<double> tiempoEntrega)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(byte));
    
            var tiempoEntregaParameter = tiempoEntrega.HasValue ?
                new ObjectParameter("TiempoEntrega", tiempoEntrega) :
                new ObjectParameter("TiempoEntrega", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_GestionarCotizacion", idCotizacionParameter, idClienteParameter, idEstadoParameter, accionParameter, tiempoEntregaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_GestionarDetalleNomina(Nullable<int> idDetalleNomina, Nullable<int> idNomina, Nullable<int> idEmpleado, Nullable<double> ajuste, Nullable<double> transporte, Nullable<byte> horasExtra, Nullable<byte> ausencia, Nullable<int> minutosTarde, Nullable<double> prestamo, Nullable<double> iNSS, Nullable<byte> accion)
        {
            var idDetalleNominaParameter = idDetalleNomina.HasValue ?
                new ObjectParameter("IdDetalleNomina", idDetalleNomina) :
                new ObjectParameter("IdDetalleNomina", typeof(int));
    
            var idNominaParameter = idNomina.HasValue ?
                new ObjectParameter("IdNomina", idNomina) :
                new ObjectParameter("IdNomina", typeof(int));
    
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("IdEmpleado", idEmpleado) :
                new ObjectParameter("IdEmpleado", typeof(int));
    
            var ajusteParameter = ajuste.HasValue ?
                new ObjectParameter("Ajuste", ajuste) :
                new ObjectParameter("Ajuste", typeof(double));
    
            var transporteParameter = transporte.HasValue ?
                new ObjectParameter("Transporte", transporte) :
                new ObjectParameter("Transporte", typeof(double));
    
            var horasExtraParameter = horasExtra.HasValue ?
                new ObjectParameter("HorasExtra", horasExtra) :
                new ObjectParameter("HorasExtra", typeof(byte));
    
            var ausenciaParameter = ausencia.HasValue ?
                new ObjectParameter("Ausencia", ausencia) :
                new ObjectParameter("Ausencia", typeof(byte));
    
            var minutosTardeParameter = minutosTarde.HasValue ?
                new ObjectParameter("MinutosTarde", minutosTarde) :
                new ObjectParameter("MinutosTarde", typeof(int));
    
            var prestamoParameter = prestamo.HasValue ?
                new ObjectParameter("Prestamo", prestamo) :
                new ObjectParameter("Prestamo", typeof(double));
    
            var iNSSParameter = iNSS.HasValue ?
                new ObjectParameter("INSS", iNSS) :
                new ObjectParameter("INSS", typeof(double));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_GestionarDetalleNomina", idDetalleNominaParameter, idNominaParameter, idEmpleadoParameter, ajusteParameter, transporteParameter, horasExtraParameter, ausenciaParameter, minutosTardeParameter, prestamoParameter, iNSSParameter, accionParameter);
        }
    
        public virtual int sp_GestionarMedida(Nullable<int> idMedida, string nombre, Nullable<byte> accion)
        {
            var idMedidaParameter = idMedida.HasValue ?
                new ObjectParameter("IdMedida", idMedida) :
                new ObjectParameter("IdMedida", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GestionarMedida", idMedidaParameter, nombreParameter, accionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_GestionarNomina(Nullable<int> idNomina, string nombre, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> idEstado, string observaciones, Nullable<byte> accion)
        {
            var idNominaParameter = idNomina.HasValue ?
                new ObjectParameter("IdNomina", idNomina) :
                new ObjectParameter("IdNomina", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_GestionarNomina", idNominaParameter, nombreParameter, fechaInicioParameter, fechaFinParameter, idEstadoParameter, observacionesParameter, accionParameter);
        }
    
        public virtual int sp_GestionarTalla(Nullable<int> idTalla, string nombre, string descripcion, Nullable<byte> accion)
        {
            var idTallaParameter = idTalla.HasValue ?
                new ObjectParameter("IdTalla", idTalla) :
                new ObjectParameter("IdTalla", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GestionarTalla", idTallaParameter, nombreParameter, descripcionParameter, accionParameter);
        }
    
        public virtual int sp_GestionarTela(Nullable<int> idTela, string nombre, Nullable<double> precio, Nullable<byte> accion)
        {
            var idTelaParameter = idTela.HasValue ?
                new ObjectParameter("IdTela", idTela) :
                new ObjectParameter("IdTela", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(double));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GestionarTela", idTelaParameter, nombreParameter, precioParameter, accionParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_NominaDetalleProduccion_Result> sp_NominaDetalleProduccion(Nullable<int> idNomina)
        {
            var idNominaParameter = idNomina.HasValue ?
                new ObjectParameter("IdNomina", idNomina) :
                new ObjectParameter("IdNomina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NominaDetalleProduccion_Result>("sp_NominaDetalleProduccion", idNominaParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerAuditoria_Result> sp_ObtenerAuditoria(string codRA)
        {
            var codRAParameter = codRA != null ?
                new ObjectParameter("CodRA", codRA) :
                new ObjectParameter("CodRA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerAuditoria_Result>("sp_ObtenerAuditoria", codRAParameter);
        }
    
        public virtual int sp_ObtenerCatalogoStandard(Nullable<int> idPieza, Nullable<int> idTalla)
        {
            var idPiezaParameter = idPieza.HasValue ?
                new ObjectParameter("IdPieza", idPieza) :
                new ObjectParameter("IdPieza", typeof(int));
    
            var idTallaParameter = idTalla.HasValue ?
                new ObjectParameter("IdTalla", idTalla) :
                new ObjectParameter("IdTalla", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ObtenerCatalogoStandard", idPiezaParameter, idTallaParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerCostosMensuales_Result> sp_ObtenerCostosMensuales(Nullable<System.DateTime> fecha, Nullable<bool> isYear)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var isYearParameter = isYear.HasValue ?
                new ObjectParameter("IsYear", isYear) :
                new ObjectParameter("IsYear", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerCostosMensuales_Result>("sp_ObtenerCostosMensuales", fechaParameter, isYearParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerCotizacion_Result> sp_ObtenerCotizacion(Nullable<int> idCotizacion)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerCotizacion_Result>("sp_ObtenerCotizacion", idCotizacionParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerDetalleCotizacion_Result> sp_ObtenerDetalleCotizacion(Nullable<int> idCotizacion)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerDetalleCotizacion_Result>("sp_ObtenerDetalleCotizacion", idCotizacionParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerDetalleNomina_Result> sp_ObtenerDetalleNomina(Nullable<int> idNomina)
        {
            var idNominaParameter = idNomina.HasValue ?
                new ObjectParameter("IdNomina", idNomina) :
                new ObjectParameter("IdNomina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerDetalleNomina_Result>("sp_ObtenerDetalleNomina", idNominaParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerListadoMatCompraCotizacion_Result> sp_ObtenerListadoMatCompraCotizacion(Nullable<int> idCotizacion)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerListadoMatCompraCotizacion_Result>("sp_ObtenerListadoMatCompraCotizacion", idCotizacionParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerListadoTelasCompraCotizacion_Result> sp_ObtenerListadoTelasCompraCotizacion(Nullable<int> idCotizacion)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerListadoTelasCompraCotizacion_Result>("sp_ObtenerListadoTelasCompraCotizacion", idCotizacionParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerNomina_Result> sp_ObtenerNomina(Nullable<int> idNomina)
        {
            var idNominaParameter = idNomina.HasValue ?
                new ObjectParameter("IdNomina", idNomina) :
                new ObjectParameter("IdNomina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerNomina_Result>("sp_ObtenerNomina", idNominaParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerTickets_Result> sp_ObtenerTickets(Nullable<int> idCotizacion, Nullable<int> noTicket)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            var noTicketParameter = noTicket.HasValue ?
                new ObjectParameter("NoTicket", noTicket) :
                new ObjectParameter("NoTicket", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerTickets_Result>("sp_ObtenerTickets", idCotizacionParameter, noTicketParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerTicketsEntregaFuncion_Result> sp_ObtenerTicketsEntregaFuncion(Nullable<int> idCotizacion, Nullable<int> noTicket)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            var noTicketParameter = noTicket.HasValue ?
                new ObjectParameter("NoTicket", noTicket) :
                new ObjectParameter("NoTicket", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerTicketsEntregaFuncion_Result>("sp_ObtenerTicketsEntregaFuncion", idCotizacionParameter, noTicketParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_AsignarUsuarioAudit(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AsignarUsuarioAudit", usuarioParameter);
        }
    
        public virtual int Sp_PermisoMenu(string controlador, string vista, string usuario, Nullable<int> idPermiso, ObjectParameter result)
        {
            var controladorParameter = controlador != null ?
                new ObjectParameter("Controlador", controlador) :
                new ObjectParameter("Controlador", typeof(string));
    
            var vistaParameter = vista != null ?
                new ObjectParameter("Vista", vista) :
                new ObjectParameter("Vista", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var idPermisoParameter = idPermiso.HasValue ?
                new ObjectParameter("idPermiso", idPermiso) :
                new ObjectParameter("idPermiso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_PermisoMenu", controladorParameter, vistaParameter, usuarioParameter, idPermisoParameter, result);
        }
    
        public virtual int sp_ObtenerHojaCorte(Nullable<int> idCotizacion, Nullable<int> noTicket)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            var noTicketParameter = noTicket.HasValue ?
                new ObjectParameter("NoTicket", noTicket) :
                new ObjectParameter("NoTicket", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ObtenerHojaCorte", idCotizacionParameter, noTicketParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerHojaEntrega_Result> sp_ObtenerHojaEntrega(Nullable<int> idCotizacion, Nullable<int> noTicket)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            var noTicketParameter = noTicket.HasValue ?
                new ObjectParameter("NoTicket", noTicket) :
                new ObjectParameter("NoTicket", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerHojaEntrega_Result>("sp_ObtenerHojaEntrega", idCotizacionParameter, noTicketParameter);
        }
    }
}
