//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtroIngresoEgreso
    {
        public int IdOtroIngresoEgreso { get; set; }
        public int IdDetalleNomina { get; set; }
        public string Concepto { get; set; }
        public double Monto { get; set; }
        public bool IsIngreso { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool regAnulado { get; set; }
    
        public virtual DetalleNomina DetalleNomina { get; set; }
    }
}
