//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pantalla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pantalla()
        {
            this.Pantalla1 = new HashSet<Pantalla>();
            this.Permiso = new HashSet<Permiso>();
            this.Rol = new HashSet<Rol>();
        }
    
        public int IdPantalla { get; set; }
        public string Nombre { get; set; }
        public string Recurso { get; set; }
        public Nullable<bool> isMenu { get; set; }
        public Nullable<int> MenuPadre { get; set; }
        public string Controlador { get; set; }
        public string Vista { get; set; }
        public Nullable<int> MenuOrden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pantalla> Pantalla1 { get; set; }
        public virtual Pantalla Pantalla2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permiso> Permiso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rol> Rol { get; set; }
    }
}
