//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioAccesorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrecioAccesorio()
        {
            this.PrecioMIDescripcionHechura = new HashSet<PrecioMIDescripcionHechura>();
        }
    
        public int IdPrecioAccesorio { get; set; }
        public int IdAccesorio { get; set; }
        public double PrecioUnitario { get; set; }
        public bool regAnulado { get; set; }
        public string cod_RA { get; set; }
    
        public virtual Accesorio Accesorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrecioMIDescripcionHechura> PrecioMIDescripcionHechura { get; set; }
    }
}
