//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionEquipoElectrico
    {
        public int IdProduccionEquipoElectrico { get; set; }
        public int IdMaquinariaEquipoElectrico { get; set; }
        public byte CantidadUsoPromedio { get; set; }
        public bool regAnulado { get; set; }
        public string Cod_RA { get; set; }
    
        public virtual MaquinariaEquipoElectrico MaquinariaEquipoElectrico { get; set; }
    }
}
