//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroAcciones
    {
        public int IdRegistro { get; set; }
        public Nullable<int> cod_RA { get; set; }
        public string Accion { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tabla { get; set; }
        public string Datos { get; set; }
    }
}
