//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw__ObtenerDetalleTickets
    {
        public int NoTicket { get; set; }
        public string NombreMedida { get; set; }
        public Nullable<double> Medida { get; set; }
        public int IdCotizacion { get; set; }
        public int IdDescripcionHechura { get; set; }
    }
}
