//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ObtenerNomina
    {
        public int Nomina { get; set; }
        public string Referencia { get; set; }
        public string Inicia { get; set; }
        public string Finaliza { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public string FechaCreacion { get; set; }
        public double PagoTotal { get; set; }
        public Nullable<double> DiasLibre { get; set; }
    }
}
