//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ObtenerCotizaciones
    {
        public int IdCotizacion { get; set; }
        public string Cod_RA { get; set; }
        public Nullable<byte> DiasEntrega { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaImpresion { get; set; }
        public string UsuarioImpresion { get; set; }
        public int IdCliente { get; set; }
        public string RazonSocial { get; set; }
        public string RUC { get; set; }
        public string Telefono { get; set; }
        public int IdPersona { get; set; }
        public string NombreContacto { get; set; }
        public string CelularContacto { get; set; }
        public string TelefonoContacto { get; set; }
        public string CorreoContacto { get; set; }
        public Nullable<double> Monto { get; set; }
        public string PorcentajeAvance { get; set; }
        public Nullable<int> Pendiente { get; set; }
    }
}
