//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ObtenerDetallesNomina
    {
        public int No_Nomina { get; set; }
        public int ColillaNo { get; set; }
        public int IdEmpleado { get; set; }
        public string Codigo { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<double> Produccion { get; set; }
        public Nullable<double> C7mo { get; set; }
        public Nullable<double> Basico { get; set; }
        public Nullable<double> Viatico { get; set; }
        public byte HorasExtra { get; set; }
        public double Ajuste { get; set; }
        public double Transporte { get; set; }
        public double TotalOtrosIngresos { get; set; }
        public byte Ausencia { get; set; }
        public int MinutosTarde { get; set; }
        public double Prestamo { get; set; }
        public double INSS { get; set; }
        public double TotalOtrosEgresos { get; set; }
    }
}
