//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ObtenerEmpleados
    {
        public int IdEmpleado { get; set; }
        public string NombreContacto { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Cedula { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public int IdOperadoraTelefonica { get; set; }
        public string OperadoraTelefonica { get; set; }
        public Nullable<bool> EstadoCivil { get; set; }
        public string codEmpleado { get; set; }
        public byte PersonasDependientes { get; set; }
        public string CelularFamiliar { get; set; }
        public string Cargo { get; set; }
        public decimal SalarioBase { get; set; }
        public bool TipoSalario { get; set; }
        public string DescSalario { get; set; }
        public bool regAnulado { get; set; }
    }
}
