//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ObtenerClientes
    {
        public int IdCliente { get; set; }
        public string RazonSocial { get; set; }
        public string RUC { get; set; }
        public string TelefonoEmpresa { get; set; }
        public string DireccionEmpresa { get; set; }
        public int CantidadEmpleados { get; set; }
        public int IdPersona { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string NombreContacto { get; set; }
        public string TelefonoContacto { get; set; }
        public string CelularContacto { get; set; }
        public int IdOperadora { get; set; }
        public string OperadoraTelefonica { get; set; }
        public string CorreoContacto { get; set; }
        public string Cedula { get; set; }
        public string DireccionContacto { get; set; }
        public Nullable<bool> EstadoCivil { get; set; }
    }
}
