//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ObtenerDetalleCotizacion
    {
        public int IdCotizacion { get; set; }
        public int IdDescripcionHechura { get; set; }
        public int IdPieza { get; set; }
        public string Pieza { get; set; }
        public string DescripcionHechura { get; set; }
        public string DescripcionHechuraOnlyCombinaciones { get; set; }
        public string DescripcionHechuraOnly { get; set; }
        public string Tela { get; set; }
        public string ColorTela { get; set; }
        public int CantidadRequerida { get; set; }
        public Nullable<int> Pendiente { get; set; }
        public Nullable<double> CostoEstimado { get; set; }
        public double PrecioUnit { get; set; }
        public Nullable<double> MargenGanancia { get; set; }
    }
}
