//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confortex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ObtenerInfoEmpresa
    {
        public string RazonSocial { get; set; }
        public string Direccion { get; set; }
        public string Telefonos { get; set; }
        public string RUC { get; set; }
    }
}
